-- Train: everything before 2024
SELECT TARGET_NEXT_DAY_RANGE_PCT, DAILY_RETURN_PCT, OVERNIGHT_GAP_PCT,
       INTRADAY_RANGE_PCT, CLOSE_LOCATION_IN_RANGE, HIGH_VS_PREV_CLOSE_PCT,
       LOW_VS_PREV_CLOSE_PCT, AVG_RANGE_5D, AVG_RANGE_10D, AVG_RANGE_20D,
       STDDEV_RETURN_5D, STDDEV_RETURN_20D, VOLUME_RATIO_20D,
       RETURN_5D, RETURN_20D, DOWN_DAYS_LAST_3, DAY_OF_WEEK, MONTH_OF_YEAR
FROM SPY_FEATURES WHERE DATE < '2024-01-01' ORDER BY DATE;

-- Validation: Jan-Jun 2024
SELECT /* same columns */ *
FROM SPY_FEATURES WHERE DATE >= '2024-01-01' AND DATE < '2024-07-01' ORDER BY DATE;

-- Test: Jul 2024 onward
SELECT /* same columns */ *
FROM SPY_FEATURES WHERE DATE >= '2024-07-01' ORDER BY DATE;